#!/usr/bin/env bash

# ACPI backlight handler script for Dell Latitude E7440
#
# Dell Latitude E7440 has a max brightness of 937

bl_dev=/sys/class/backlight/intel_backlight
step=$(( $(cat ${bl_dev}/max_brightness) / 10 ))

case $1 in
  -) echo $(($(< ${bl_dev}/brightness) - step)) > ${bl_dev}/brightness; exit 0;;
  +) echo $(($(< ${bl_dev}/brightness) + step)) > ${bl_dev}/brightness; exit 0;;
  *)
    echo "Usage: $0 {+|-}"
    exit 1
    ;;
esac
