#!/usr/bin/env sh

# Lid events handler script for Intel backlight devices

DEVICE=/sys/class/backlight/intel_backlight
MAX_BRIGHTNESS=$(cat "${DEVICE}/max_brightness")
SAVE_FILE=/run/backlight_level_save

case $1 in
  open)
    # Get previous brightness and wake up the display
    if [ -f "${SAVE_FILE}" ]; then
      cat "${SAVE_FILE}" > "${DEVICE}/brightness"
      rm "${SAVE_FILE}"
    else
      printf "%d" $(( MAX_BRIGHTNESS / 2)) > "${DEVICE}/brightness"
    fi
    exit 0
    ;;
  close)
    # Save current brightness and turn off the display
    cat "${DEVICE}/brightness" > "${SAVE_FILE}"
    printf "%d" 0 > "${DEVICE}/brightness"
    exit 0
    ;;
  *)
    printf "\n"
    printf "Lid handler script"
    printf "\n\n"
    printf "Usage: %s {open|close}\n" "$0"
    printf "\n"
    printf "\topen\tRestore backlight brightness on lid open\n"
    printf "\tclose\tTurn off backlight brightness on lid close\n"
    printf "\n"
    exit 1
    ;;
esac
