#!/usr/bin/env sh

# Lid events handler script for Dell Latitude E7440
#
# Dell Latitude E7440 has a max brightness of 937

bl_dev=/sys/class/backlight/intel_backlight

case $1 in
  open)
    # Get previous brightness and wake up the display
    if [ -f /run/backlight_level_save ]; then
      cat /run/backlight_level_save > ${bl_dev}/brightness
      rm /run/backlight_level_save
    else
      echo $(( $(cat ${bl_dev}/max_brightness) / 2)) > ${bl_dev}/brightness
    fi
    exit 0
    ;;
  close)
    # Save current brightness and turn off the display
    cat ${bl_dev}/brightness > /run/backlight_level_save
    echo 0 > ${bl_dev}/brightness
    exit 0
    ;;
  *)
    echo "Usage: $0 {open|close}"
    exit 1
    ;;
esac